package me.mrCookieSlime.Slimefun.Setup;

import me.mrCookieSlime.Slimefun.Lists.SlimefunItems;
import me.mrCookieSlime.Slimefun.Objects.Research;
import me.mrCookieSlime.Slimefun.api.Slimefun;

import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

public class ResearchSetup {

    public static void setupResearches() {
        Slimefun.registerResearch(new Research(0, "击退手杖与击飞手杖", 8, 600, 0, 0), SlimefunItems.GRANDMAS_WALKING_STICK, SlimefunItems.GRANDPAS_WALKING_STICK);
        Slimefun.registerResearch(new Research(1, "便携式合成台", 5, 300, 0, 0), SlimefunItems.PORTABLE_CRAFTER);
        Slimefun.registerResearch(new Research(2, "幸运曲奇", 5, 500, 0, 0), SlimefunItems.FORTUNE_COOKIE);
        Slimefun.registerResearch(new Research(4, "便携式垃圾桶", 5, 300, 0, 0), SlimefunItems.PORTABLE_DUSTBIN);
        Slimefun.registerResearch(new Research(5, "牛肉干", 3, 300, 0, 0), SlimefunItems.BEEF_JERKY);
        Slimefun.registerResearch(new Research(6, "护甲制作台", 12, 2500, 1, 0), SlimefunItems.ARMOR_FORGE);
        Slimefun.registerResearch(new Research(8, "魔法之尘", 8, 750, 0, 0), new ItemStack[]{SlimefunItems.MAGIC_LUMP_1, SlimefunItems.MAGIC_LUMP_2, SlimefunItems.MAGIC_LUMP_3, SlimefunItems.ENDER_LUMP_1, SlimefunItems.ENDER_LUMP_2, SlimefunItems.ENDER_LUMP_3});
        Slimefun.registerResearch(new Research(9, "末影背包", 8, 1500, 1, 0), new ItemStack[]{SlimefunItems.ENDER_BACKPACK});
        Slimefun.registerResearch(new Research(7, "萤石护甲", 10, 500, 0, 0), new ItemStack[]{SlimefunItems.GLOWSTONE_HELMET, SlimefunItems.GLOWSTONE_CHESTPLATE, SlimefunItems.GLOWSTONE_LEGGINGS, SlimefunItems.GLOWSTONE_BOOTS});
        Slimefun.registerResearch(new Research(10, "末影护甲", 18, 800, 1, 0), new ItemStack[]{SlimefunItems.ENDER_HELMET, SlimefunItems.ENDER_CHESTPLATE, SlimefunItems.ENDER_LEGGINGS, SlimefunItems.ENDER_BOOTS});
        Slimefun.registerResearch(new Research(11, "注魔末影之眼", 6, 500, 0, 0), new ItemStack[]{SlimefunItems.MAGIC_EYE_OF_ENDER});
        Slimefun.registerResearch(new Research(12, "魔法糖果", 4, 0, 0, 0), new ItemStack[]{SlimefunItems.MAGIC_SUGAR});
        Slimefun.registerResearch(new Research(13, "怪兽牛肉干", 5), new ItemStack[]{SlimefunItems.MONSTER_JERKY});
        Slimefun.registerResearch(new Research(14, "硬化粘液护甲", 5, 600, 0, 0), new ItemStack[]{SlimefunItems.SLIME_HELMET, SlimefunItems.SLIME_CHESTPLATE, SlimefunItems.SLIME_LEGGINGS, SlimefunItems.SLIME_BOOTS});
        Slimefun.registerResearch(new Research(15, "斩首巨剑", 12, 2500, 1, 0), new ItemStack[]{SlimefunItems.SWORD_OF_BEHEADING});
        Slimefun.registerResearch(new Research(16, "基础电路板", 8, 300, 0, 0), new ItemStack[]{SlimefunItems.BASIC_CIRCUIT_BOARD});
        Slimefun.registerResearch(new Research(17, "先进电路板", 9, 500, 0, 0), new ItemStack[]{SlimefunItems.ADVANCED_CIRCUIT_BOARD});
        Slimefun.registerResearch(new Research(18, "高炉", 10, 1200, 1, 0), new ItemStack[]{SlimefunItems.SMELTERY});
        Slimefun.registerResearch(new Research(19, "铁器时代", 11, 600, 0, 0), new ItemStack[]{SlimefunItems.STEEL_INGOT});
        Slimefun.registerResearch(new Research(20, "能量存储介质", 12, 1500, 1, 0), new ItemStack[]{SlimefunItems.SULFATE, SlimefunItems.POWER_CRYSTAL});
        Slimefun.registerResearch(new Research(21, "电池", 10, 750), new ItemStack[]{SlimefunItems.BATTERY});
        Slimefun.registerResearch(new Research(22, "钢板", 14, 800, 0, 0), new ItemStack[]{SlimefunItems.STEEL_PLATE});
        Slimefun.registerResearch(new Research(23, "钢制推进器", 14, 750, 0, 0), new ItemStack[]{SlimefunItems.STEEL_THRUSTER});
        Slimefun.registerResearch(new Research(24, "降落伞", 15, 450), new ItemStack[]{SlimefunItems.PARACHUTE});
        Slimefun.registerResearch(new Research(25, "钩爪", 15, 1200, 1), new ItemStack[]{SlimefunItems.GRAPPLING_HOOK, SlimefunItems.HOOK, SlimefunItems.CHAIN});
        Slimefun.registerResearch(new Research(26, "喷气背包", 28, 4500, 1, 1), new ItemStack[]{SlimefunItems.DURALUMIN_JETPACK, SlimefunItems.BILLON_JETPACK, SlimefunItems.SOLDER_JETPACK, SlimefunItems.STEEL_JETPACK, SlimefunItems.DAMASCUS_STEEL_JETPACK, SlimefunItems.REINFORCED_ALLOY_JETPACK});
        Slimefun.registerResearch(new Research(27, "多用工具", 22, 3500, 1, 1), new ItemStack[]{SlimefunItems.DURALUMIN_MULTI_TOOL, SlimefunItems.SOLDER_MULTI_TOOL, SlimefunItems.BILLON_MULTI_TOOL, SlimefunItems.STEEL_MULTI_TOOL, SlimefunItems.DAMASCUS_STEEL_MULTI_TOOL, SlimefunItems.REINFORCED_ALLOY_MULTI_TOOL});
        Slimefun.registerResearch(new Research(28, "光伏动力", 18, 3000, 1, 0), new ItemStack[]{SlimefunItems.SOLAR_PANEL, SlimefunItems.SOLAR_HELMET});
        Slimefun.registerResearch(new Research(29, "元素法杖", 17, 3500, 1, 0), new ItemStack[]{SlimefunItems.STAFF_ELEMENTAL});
        Slimefun.registerResearch(new Research(30, "粉碎机", 12, 800, 1), new ItemStack[]{SlimefunItems.GRIND_STONE});
        Slimefun.registerResearch(new Research(31, "仙人掌护甲", 5, 600), new ItemStack[]{SlimefunItems.CACTUS_BOOTS, SlimefunItems.CACTUS_CHESTPLATE, SlimefunItems.CACTUS_HELMET, SlimefunItems.CACTUS_LEGGINGS});
        Slimefun.registerResearch(new Research(32, "淘金盘", 5, 300), new ItemStack[]{SlimefunItems.GOLD_PAN});
        Slimefun.registerResearch(new Research(33, "魔法书", 5, 800), new ItemStack[]{SlimefunItems.MAGICAL_BOOK_COVER});
        Slimefun.registerResearch(new Research(34, "基础金属", 14, 1500, 1), new ItemStack[]{SlimefunItems.COPPER_INGOT, SlimefunItems.TIN_INGOT, SlimefunItems.SILVER_INGOT, SlimefunItems.LEAD_INGOT, SlimefunItems.ALUMINUM_INGOT, SlimefunItems.ZINC_INGOT, SlimefunItems.MAGNESIUM_INGOT});
        Slimefun.registerResearch(new Research(35, "矿物加倍", 12, 1200, 1), new ItemStack[]{SlimefunItems.ORE_CRUSHER});
        Slimefun.registerResearch(new Research(36, "青铜锭", 8, 600), new ItemStack[]{SlimefunItems.BRONZE_INGOT});
        Slimefun.registerResearch(new Research(37, "高级合金", 22, 3500, 1, 1), new ItemStack[]{SlimefunItems.BILLON_INGOT, SlimefunItems.DURALUMIN_INGOT, SlimefunItems.ALUMINUM_BRASS_INGOT, SlimefunItems.ALUMINUM_BRONZE_INGOT, SlimefunItems.SOLDER_INGOT, SlimefunItems.CORINTHIAN_BRONZE_INGOT, SlimefunItems.BRASS_INGOT});
        Slimefun.registerResearch(new Research(38, "碳纤维科技", 15, 1800, 1, 0), new ItemStack[]{SlimefunItems.COMPRESSOR, SlimefunItems.CARBON});
        Slimefun.registerResearch(new Research(39, "量产面粉", 5, 300), new ItemStack[]{SlimefunItems.WHEAT_FLOUR});
        Slimefun.registerResearch(new Research(40, "镀金锻钢护甲", 16, 2000, 1), new ItemStack[]{SlimefunItems.GILDED_IRON_HELMET, SlimefunItems.GILDED_IRON_CHESTPLATE, SlimefunItems.GILDED_IRON_LEGGINGS, SlimefunItems.GILDED_IRON_BOOTS});
        Slimefun.registerResearch(new Research(41, "人造钻石", 20, 1500, 1), new ItemStack[]{SlimefunItems.COMPRESSED_CARBON, SlimefunItems.CARBON_CHUNK, SlimefunItems.SYNTHETIC_DIAMOND});
        Slimefun.registerResearch(new Research(42, "真空压缩机", 14, 3500, 0, 1), new ItemStack[]{SlimefunItems.PRESSURE_CHAMBER});
        Slimefun.registerResearch(new Research(43, "人造蓝宝石", 16, 1500, 1), new ItemStack[]{SlimefunItems.SYNTHETIC_SAPPHIRE});
        Slimefun.registerResearch(new Research(45, "大马士革钢", 17, 2000, 1), new ItemStack[]{SlimefunItems.DAMASCUS_STEEL_INGOT});
        Slimefun.registerResearch(new Research(46, "大马士革护甲", 18, 2500, 1), new ItemStack[]{SlimefunItems.DAMASCUS_STEEL_HELMET, SlimefunItems.DAMASCUS_STEEL_CHESTPLATE, SlimefunItems.DAMASCUS_STEEL_LEGGINGS, SlimefunItems.DAMASCUS_STEEL_BOOTS});
        Slimefun.registerResearch(new Research(47, "硬化金属", 22, 3500, 0, 1), new ItemStack[]{SlimefunItems.HARDENED_METAL_INGOT, SlimefunItems.REINFORCED_ALLOY_INGOT});
        Slimefun.registerResearch(new Research(48, "黑色钻石", 26, 3500, 0, 1), new ItemStack[]{SlimefunItems.RAW_CARBONADO, SlimefunItems.CARBONADO});
        Slimefun.registerResearch(new Research(50, "魔法工作台", 12, 1500, 1), new ItemStack[]{SlimefunItems.MAGIC_WORKBENCH});
        Slimefun.registerResearch(new Research(51, "风之法杖", 17, 2500, 1), new ItemStack[]{SlimefunItems.STAFF_WIND});
        Slimefun.registerResearch(new Research(52, "复合护甲", 26, 4000, 1), new ItemStack[]{SlimefunItems.REINFORCED_ALLOY_HELMET, SlimefunItems.REINFORCED_ALLOY_CHESTPLATE, SlimefunItems.REINFORCED_ALLOY_LEGGINGS, SlimefunItems.REINFORCED_ALLOY_BOOTS});
        Slimefun.registerResearch(new Research(53, "洗矿机", 5, 1200, 1), new ItemStack[]{SlimefunItems.ORE_WASHER, SlimefunItems.STONE_CHUNK, SlimefunItems.SIFTED_ORE});
        Slimefun.registerResearch(new Research(54, "高纯度金", 7, 600), new ItemStack[]{SlimefunItems.GOLD_4K, SlimefunItems.GOLD_6K, SlimefunItems.GOLD_8K, SlimefunItems.GOLD_10K, SlimefunItems.GOLD_12K, SlimefunItems.GOLD_14K, SlimefunItems.GOLD_16K, SlimefunItems.GOLD_18K, SlimefunItems.GOLD_20K, SlimefunItems.GOLD_22K, SlimefunItems.GOLD_24K});
        Slimefun.registerResearch(new Research(55, "Silicon Valley", 12, 1500), new ItemStack[]{SlimefunItems.SILICON, SlimefunItems.FERROSILICON});
        Slimefun.registerResearch(new Research(56, "Fire Staff", 9, 1200, 1), new ItemStack[]{SlimefunItems.STAFF_FIRE});
        Slimefun.registerResearch(new Research(57, "Smelters Pickaxe", 17, 3500, 1), new ItemStack[]{SlimefunItems.AUTO_SMELT_PICKAXE});
        Slimefun.registerResearch(new Research(58, "Common Talisman", 14, 1200), new ItemStack[]{SlimefunItems.TALISMAN});
        Slimefun.registerResearch(new Research(59, "Talisman of the Anvil", 18, 2500, 1), new ItemStack[]{SlimefunItems.TALISMAN_ANVIL});
        Slimefun.registerResearch(new Research(60, "Talisman of the Miner", 18, 2500, 1), new ItemStack[]{SlimefunItems.TALISMAN_MINER});
        Slimefun.registerResearch(new Research(61, "Talisman of the Hunter", 18, 2500, 1), new ItemStack[]{SlimefunItems.TALISMAN_HUNTER});
        Slimefun.registerResearch(new Research(62, "Talisman of the Lava Walker", 18, 2500, 1), new ItemStack[]{SlimefunItems.TALISMAN_LAVA});
        Slimefun.registerResearch(new Research(63, "Talisman of the Water Breather", 18, 2500, 1), new ItemStack[]{SlimefunItems.TALISMAN_WATER});
        Slimefun.registerResearch(new Research(64, "Talisman of the Angel", 18, 2500, 1), new ItemStack[]{SlimefunItems.TALISMAN_ANGEL});
        Slimefun.registerResearch(new Research(65, "Talisman of the Firefighter", 18, 2500, 1), new ItemStack[]{SlimefunItems.TALISMAN_FIRE});
        Slimefun.registerResearch(new Research(67, "Firey Situation", 14, 1200), SlimefunItems.LAVA_CRYSTAL);
        Slimefun.registerResearch(new Research(68, "Talisman of the Magician", 20, 2800, 1), SlimefunItems.TALISMAN_MAGICIAN);
        Slimefun.registerResearch(new Research(69, "Talisman of the Traveller", 20, 2800, 1), SlimefunItems.TALISMAN_TRAVELLER);
        Slimefun.registerResearch(new Research(70, "Talisman of the Warrior", 20, 2800, 1), SlimefunItems.TALISMAN_WARRIOR);
        Slimefun.registerResearch(new Research(71, "Talisman of the Knight", 20, 2800, 1), SlimefunItems.TALISMAN_KNIGHT);
        Slimefun.registerResearch(new Research(72, "Shiny Iron", 11, 1500), SlimefunItems.GILDED_IRON);
        Slimefun.registerResearch(new Research(73, "Fake Gem", 17, 1200), SlimefunItems.SYNTHETIC_EMERALD);
        Slimefun.registerResearch(new Research(74, "Chainmail Armor", 8, 1500), new ItemStack(Material.CHAINMAIL_HELMET), new ItemStack(Material.CHAINMAIL_CHESTPLATE), new ItemStack(Material.CHAINMAIL_LEGGINGS), new ItemStack(Material.CHAINMAIL_BOOTS));
        Slimefun.registerResearch(new Research(75, "Talisman of the Whirlwind", 19, 2500, 1), SlimefunItems.TALISMAN_WHIRLWIND);
        Slimefun.registerResearch(new Research(76, "Talisman of the Wizard", 22, 2800, 1), SlimefunItems.TALISMAN_WIZARD);
        Slimefun.registerResearch(new Research(77, "Lumber Axe", 21, 25000, 0, 1), SlimefunItems.LUMBER_AXE);
        Slimefun.registerResearch(new Research(79, "Hazmat Suit", 21, 3500), SlimefunItems.SCUBA_HELMET, SlimefunItems.HAZMATSUIT_CHESTPLATE, SlimefunItems.HAZMATSUIT_LEGGINGS, SlimefunItems.RUBBER_BOOTS);
        Slimefun.registerResearch(new Research(80, "Radioactive", 30, 5000, 0, 1), SlimefunItems.TINY_URANIUM, SlimefunItems.SMALL_URANIUM, SlimefunItems.URANIUM);
        Slimefun.registerResearch(new Research(81, "Ore Purification", 25, 5000, 1), SlimefunItems.CRUSHED_ORE, SlimefunItems.PULVERIZED_ORE, SlimefunItems.PURE_ORE_CLUSTER);
        Slimefun.registerResearch(new Research(84, "Redstone Alloy", 16, 1500), SlimefunItems.REDSTONE_ALLOY);
        Slimefun.registerResearch(new Research(85, "Top Tier Machines", 32, 6000, 0, 1), SlimefunItems.CARBONADO_MULTI_TOOL, SlimefunItems.CARBONADO_JETPACK, SlimefunItems.CARBONADO_JETBOOTS);
        Slimefun.registerResearch(new Research(86, "First Aid", 9, 600), SlimefunItems.CLOTH, SlimefunItems.RAG, SlimefunItems.BANDAGE, SlimefunItems.SPLINT, SlimefunItems.CAN, SlimefunItems.VITAMINS, SlimefunItems.MEDICINE);
        Slimefun.registerResearch(new Research(87, "Shiny Armor", 13, 2500, 1), SlimefunItems.GOLD_HELMET, SlimefunItems.GOLD_CHESTPLATE, SlimefunItems.GOLD_LEGGINGS, SlimefunItems.GOLD_BOOTS);
        Slimefun.registerResearch(new Research(89, "Night Vision Goggles", 10, 1500, 1), SlimefunItems.NIGHT_VISION_GOGGLES);
        Slimefun.registerResearch(new Research(90, "Pickaxe of Containment", 60, 96000, 1, 1), SlimefunItems.PICKAXE_OF_CONTAINMENT, SlimefunItems.BROKEN_SPAWNER);
        Slimefun.registerResearch(new Research(91, "Hercules Pickaxe", 28, 5000, 0, 1), SlimefunItems.HERCULES_PICKAXE);
        Slimefun.registerResearch(new Research(92, "Saw Mill", 6, 900), SlimefunItems.SAW_MILL);
        Slimefun.registerResearch(new Research(93, "Slimy Steel Armor", 27, 3500, 1), SlimefunItems.SLIME_HELMET_STEEL, SlimefunItems.SLIME_CHESTPLATE_STEEL, SlimefunItems.SLIME_LEGGINGS_STEEL, SlimefunItems.SLIME_BOOTS_STEEL);
        Slimefun.registerResearch(new Research(94, "Blade of Vampires", 26, 1800, 1), SlimefunItems.BLADE_OF_VAMPIRES);
        Slimefun.registerResearch(new Research(95, "Lazy Mining", 40, 8000, 0, 1), SlimefunItems.DIGITAL_MINER);
        Slimefun.registerResearch(new Research(96, "Water Staff", 8, 1500), SlimefunItems.STAFF_WATER);
        Slimefun.registerResearch(new Research(97, "Golden City", 19, 1200), SlimefunItems.GOLD_24K_BLOCK);
        Slimefun.registerResearch(new Research(98, "Advanced Mining 101", 42, 15000, 0, 1), SlimefunItems.ADVANCED_DIGITAL_MINER);
        Slimefun.registerResearch(new Research(99, "Composting Dirt", 15, 6000, 0, 1), SlimefunItems.COMPOSTER);
        Slimefun.registerResearch(new Research(100, "Farmer Shoes", 4, 600), SlimefunItems.FARMER_SHOES);
        Slimefun.registerResearch(new Research(101, "Explosive Pickaxe", 28, 16000, 0, 1), SlimefunItems.EXPLOSIVE_PICKAXE);
        Slimefun.registerResearch(new Research(102, "Automated Gold Pan", 17, 6000, 0, 1), SlimefunItems.AUTOMATED_PANNING_MACHINE);
        Slimefun.registerResearch(new Research(103, "Boots of the Stomper", 19, 1200), SlimefunItems.BOOTS_OF_THE_STOMPER);
        Slimefun.registerResearch(new Research(104, "Pickaxe of the Seeker", 19, 2500, 1), SlimefunItems.PICKAXE_OF_THE_SEEKER);
        Slimefun.registerResearch(new Research(105, "Backpacks", 15, 3500, 1), SlimefunItems.BACKPACK_LARGE, SlimefunItems.BACKPACK_MEDIUM, SlimefunItems.BACKPACK_SMALL);
        Slimefun.registerResearch(new Research(106, "Woven Backpack", 19, 3000, 1), SlimefunItems.WOVEN_BACKPACK);
        Slimefun.registerResearch(new Research(107, "Crucible", 13, 1500, 1), SlimefunItems.CRUCIBLE);
        Slimefun.registerResearch(new Research(108, "Gilded Backpack", 22, 3500, 1), SlimefunItems.GILDED_BACKPACK);
        Slimefun.registerResearch(new Research(110, "Being a Tank", 28, 5000, 0, 1), SlimefunItems.HEAVY_METAL_HELMET, SlimefunItems.HEAVY_METAL_CHESTPLATE, SlimefunItems.HEAVY_METAL_LEGGINGS, SlimefunItems.HEAVY_METAL_BOOTS);
        Slimefun.registerResearch(new Research(111, "Armored Jetpack", 27, 2500, 0, 1), SlimefunItems.ARMORED_JETPACK);
        Slimefun.registerResearch(new Research(112, "Ender Talismans", 28, 5000, 0, 1));
        Slimefun.registerResearch(new Research(115, "Even more Ores", 10, 1500, 1), SlimefunItems.NICKEL_INGOT, SlimefunItems.COBALT_INGOT);
        Slimefun.registerResearch(new Research(116, "Magnetic Metals", 16, 1200, 1), SlimefunItems.MAGNET);
        Slimefun.registerResearch(new Research(117, "Infused Magnets", 18, 1500, 1), SlimefunItems.INFUSED_MAGNET);
        Slimefun.registerResearch(new Research(118, "Speedy Pickaxe", 14, 2500, 1), SlimefunItems.COBALT_PICKAXE);
        Slimefun.registerResearch(new Research(119, "Necromancy", 19, 6000, 0, 1), SlimefunItems.NECROTIC_SKULL, SlimefunItems.ESSENCE_OF_AFTERLIFE);
        Slimefun.registerResearch(new Research(120, "Soulbound Storage", 22, 2500, 1), SlimefunItems.BOUND_BACKPACK);
        Slimefun.registerResearch(new Research(121, "Jet Boots", 25, 3500, 1), SlimefunItems.DURALUMIN_JETBOOTS, SlimefunItems.BILLON_JETBOOTS, SlimefunItems.SOLDER_JETBOOTS, SlimefunItems.STEEL_JETBOOTS, SlimefunItems.DAMASCUS_STEEL_JETBOOTS, SlimefunItems.REINFORCED_ALLOY_JETBOOTS);
        Slimefun.registerResearch(new Research(122, "Armored Jet Boots", 27, 5000, 0, 1), SlimefunItems.ARMORED_JETBOOTS);
        Slimefun.registerResearch(new Research(123, "Seismic Axe", 29, 3500, 0, 1), SlimefunItems.SEISMIC_AXE);
        Slimefun.registerResearch(new Research(124, "Pickaxe of Vein Mining", 29, 5000, 0, 1), SlimefunItems.PICKAXE_OF_VEIN_MINING);
        Slimefun.registerResearch(new Research(125, "Soulbound Weapons", 29, 1500, 1), SlimefunItems.SOULBOUND_SWORD, SlimefunItems.SOULBOUND_BOW);
        Slimefun.registerResearch(new Research(126, "Soulbound Tools", 29, 1500, 1), SlimefunItems.SOULBOUND_PICKAXE, SlimefunItems.SOULBOUND_AXE, SlimefunItems.SOULBOUND_SHOVEL, SlimefunItems.SOULBOUND_HOE);
        Slimefun.registerResearch(new Research(127, "Soulbound Armor", 29, 1500, 1), SlimefunItems.SOULBOUND_HELMET, SlimefunItems.SOULBOUND_CHESTPLATE, SlimefunItems.SOULBOUND_LEGGINGS, SlimefunItems.SOULBOUND_BOOTS);
        Slimefun.registerResearch(new Research(129, "Delicious Drinks", 29, 2500, 1), SlimefunItems.JUICER, SlimefunItems.APPLE_JUICE, SlimefunItems.MELON_JUICE, SlimefunItems.CARROT_JUICE, SlimefunItems.PUMPKIN_JUICE);
        Slimefun.registerResearch(new Research(130, "Repairing Spawners", 15, 12000, 15, 5), SlimefunItems.REPAIRED_SPAWNER);
        Slimefun.registerResearch(new Research(131, "HO HO HO", 1));
        Slimefun.registerResearch(new Research(132, "Enhanced Furnace", 7, 2500, 1), SlimefunItems.ENHANCED_FURNACE, SlimefunItems.ENHANCED_FURNACE_2);
        Slimefun.registerResearch(new Research(133, "Better Furnaces", 18, 3500, 1), SlimefunItems.ENHANCED_FURNACE_3, SlimefunItems.ENHANCED_FURNACE_4, SlimefunItems.ENHANCED_FURNACE_5, SlimefunItems.ENHANCED_FURNACE_6, SlimefunItems.ENHANCED_FURNACE_7);
        Slimefun.registerResearch(new Research(134, "High Tier Furnace", 29, 5000, 1), SlimefunItems.ENHANCED_FURNACE_8, SlimefunItems.ENHANCED_FURNACE_9, SlimefunItems.ENHANCED_FURNACE_10, SlimefunItems.ENHANCED_FURNACE_11);
        Slimefun.registerResearch(new Research(135, "Reinforced Furnace", 32, 8000, 0, 1), SlimefunItems.REINFORCED_FURNACE);
        Slimefun.registerResearch(new Research(136, "Carbonado Edged Furnace", 35, 12000, 0, 3), SlimefunItems.CARBONADO_EDGED_FURNACE);
        Slimefun.registerResearch(new Research(137, "Heating up", 32, 2500, 1), SlimefunItems.ELECTRO_MAGNET, SlimefunItems.ELECTRIC_MOTOR, SlimefunItems.HEATING_COIL);
        Slimefun.registerResearch(new Research(138, "Block Placer", 17, 2500, 1), SlimefunItems.BLOCK_PLACER);
        Slimefun.registerResearch(new Research(139, "Lazy Panning", 29, 6000, 0, 1), SlimefunItems.AUTOMATED_PANNING_MACHINE);
        Slimefun.registerResearch(new Research(142, "Turning things around", 38, 6000, 2, 1), SlimefunItems.SCROLL_OF_DIMENSIONAL_TELEPOSITION);
        Slimefun.registerResearch(new Research(143, "Robin Hood", 22, 3500, 1), SlimefunItems.EXPLOSIVE_BOW, SlimefunItems.ICY_BOW);
        Slimefun.registerResearch(new Research(144, "Sharing with friends", 30, 2500, 1), SlimefunItems.TOME_OF_KNOWLEDGE_SHARING);
        Slimefun.registerResearch(new Research(145, "XP Storage", 13, 1500, 1), SlimefunItems.FLASK_OF_KNOWLEDGE);
        Slimefun.registerResearch(new Research(146, "Withstanding Explosions", 15, 1800, 1), SlimefunItems.REINFORCED_PLATE, SlimefunItems.HARDENED_GLASS);
        Slimefun.registerResearch(new Research(148, "Happy Easter", 1));
        Slimefun.registerResearch(new Research(149, "Golden potion", 24, 1200, 1), SlimefunItems.GOLDE_APPLE_JUICE);
        Slimefun.registerResearch(new Research(150, "Portable Beverages", 24, 1500, 0, 1), SlimefunItems.COOLING_UNIT, SlimefunItems.COOLER);
        Slimefun.registerResearch(new Research(151, "Ancient Altar", 15, 9000, 0, 3), SlimefunItems.ANCIENT_PEDESTAL, SlimefunItems.ANCIENT_ALTAR);
        Slimefun.registerResearch(new Research(152, "Wither-Proof Obsidian", 21, 3500, 0, 1), SlimefunItems.WITHER_PROOF_OBSIDIAN);
        Slimefun.registerResearch(new Research(154, "Upgraded Solar Cells", 26, 5000, 0, 1), SlimefunItems.SOLAR_ARRAY);
        Slimefun.registerResearch(new Research(155, "Elemental Runes", 15, 2200, 1), SlimefunItems.BLANK_RUNE, SlimefunItems.RUNE_EARTH, SlimefunItems.RUNE_WATER, SlimefunItems.RUNE_AIR, SlimefunItems.RUNE_FIRE);
        Slimefun.registerResearch(new Research(156, "Purple Runes", 18, 2500, 1), SlimefunItems.RUNE_ENDER, SlimefunItems.RUNE_RAINBOW);
        Slimefun.registerResearch(new Research(157, "Infernal Bonemeal", 12, 1200, 1), SlimefunItems.INFERNAL_BONEMEAL);
        Slimefun.registerResearch(new Research(158, "Rainbow Blocks", 24, 2500, 1), SlimefunItems.RAINBOW_CLAY, SlimefunItems.RAINBOW_GLASS, SlimefunItems.RAINBOW_GLASS_PANE, SlimefunItems.RAINBOW_WOOL);
        Slimefun.registerResearch(new Research(159, "Infused Hopper", 22, 3500, 0, 1), SlimefunItems.INFUSED_HOPPER);
        Slimefun.registerResearch(new Research(160, "Wither-Proof Glass", 20, 1500, 3, 1), SlimefunItems.WITHER_PROOF_GLASS);
        Slimefun.registerResearch(new Research(161, "Duct Tape", 14, 1500, 1), SlimefunItems.DUCT_TAPE);
        Slimefun.registerResearch(new Research(162, "Plastic", 25, 2800, 1), SlimefunItems.PLASTIC_SHEET);
        Slimefun.registerResearch(new Research(163, "Memory Core", 28, 5000, 0, 1), SlimefunItems.ANDROID_MEMORY_CORE);
        Slimefun.registerResearch(new Research(164, "Oil", 30, 3500, 0, 1), SlimefunItems.BUCKET_OF_OIL, SlimefunItems.OIL_PUMP);
        Slimefun.registerResearch(new Research(165, "Fuel", 30, 3500, 0, 1), SlimefunItems.BUCKET_OF_FUEL, SlimefunItems.REFINERY);
        Slimefun.registerResearch(new Research(166, "Holograms", 36, 5000, 0, 3), SlimefunItems.HOLOGRAM_PROJECTOR);
        Slimefun.registerResearch(new Research(167, "Tier 1 Capacitors", 25, 3000, 1), SlimefunItems.SMALL_CAPACITOR, SlimefunItems.MEDIUM_CAPACITOR, SlimefunItems.BIG_CAPACITOR);
        Slimefun.registerResearch(new Research(168, "Tier 2 Capacitors", 32, 5000, 3, 1), SlimefunItems.LARGE_CAPACITOR, SlimefunItems.CARBONADO_EDGED_CAPACITOR);
        Slimefun.registerResearch(new Research(169, "Solar Power Plant", 14, 2500, 1), SlimefunItems.SOLAR_GENERATOR);
        Slimefun.registerResearch(new Research(170, "Powered Furnace", 15, 3000, 1), SlimefunItems.ELECTRIC_FURNACE);
        Slimefun.registerResearch(new Research(171, "Crushing and Grinding", 20, 3500, 1), SlimefunItems.ELECTRIC_ORE_GRINDER, SlimefunItems.ELECTRIC_INGOT_PULVERIZER);
        Slimefun.registerResearch(new Research(172, "Heated Pressure Chamber", 22, 5000, 0, 1), SlimefunItems.HEATED_PRESSURE_CHAMBER);
        Slimefun.registerResearch(new Research(173, "Coal Generator", 18, 2500, 1), SlimefunItems.COAL_GENERATOR);
        Slimefun.registerResearch(new Research(173, "Bio-Reactor", 18, 2500, 1), SlimefunItems.BIO_REACTOR);
        Slimefun.registerResearch(new Research(174, "Automatic Enchanting and Disenchanting", 24, 18000, 0, 3), SlimefunItems.AUTO_ENCHANTER, SlimefunItems.AUTO_DISENCHANTER);
        Slimefun.registerResearch(new Research(175, "Automatic Anvil", 34, 25000, 0, 3), SlimefunItems.AUTO_ANVIL, SlimefunItems.AUTO_ANVIL_2);
        Slimefun.registerResearch(new Research(176, "Power Measurement", 10, 1200, 1), SlimefunItems.MULTIMETER);
        Slimefun.registerResearch(new Research(177, "Basic GPS Setup", 28, 4000, 0, 1), SlimefunItems.GPS_TRANSMITTER, SlimefunItems.GPS_CONTROL_PANEL, SlimefunItems.GPS_MARKER_TOOL);
        Slimefun.registerResearch(new Research(178, "GPS Emergency Waypoint", 30, 2000, 0, 1), SlimefunItems.GPS_EMERGENCY_TRANSMITTER);
        Slimefun.registerResearch(new Research(179, "Programmable Androids", 50, 20000, 0, 3), SlimefunItems.PROGRAMMABLE_ANDROID, SlimefunItems.PROGRAMMABLE_ANDROID_FARMER, SlimefunItems.PROGRAMMABLE_ANDROID_BUTCHER, SlimefunItems.PROGRAMMABLE_ANDROID_FISHERMAN, SlimefunItems.PROGRAMMABLE_ANDROID_MINER, SlimefunItems.PROGRAMMABLE_ANDROID_WOODCUTTER);
        Slimefun.registerResearch(new Research(180, "Android Interfaces", 26, 12000, 5, 1), SlimefunItems.ANDROID_INTERFACE_FUEL, SlimefunItems.ANDROID_INTERFACE_ITEMS);
        Slimefun.registerResearch(new Research(181, "GEO-Scans", 30, 6000, 0, 1), SlimefunItems.GPS_GEO_SCANNER);
        Slimefun.registerResearch(new Research(182, "Combustion Reactor", 38, 6000,5, 2), SlimefunItems.COMBUSTION_REACTOR);
        Slimefun.registerResearch(new Research(183, "Teleporter Base Components", 42, 15000, 0, 1), SlimefunItems.GPS_TELEPORTATION_MATRIX, SlimefunItems.GPS_TELEPORTER_PYLON);
        Slimefun.registerResearch(new Research(184, "Teleporter Activation", 36, 12000, 0, 1), SlimefunItems.GPS_ACTIVATION_DEVICE_PERSONAL, SlimefunItems.GPS_ACTIVATION_DEVICE_SHARED);
        Slimefun.registerResearch(new Research(185, "Upgraded Solar Generators", 28, 5000, 0, 1), SlimefunItems.SOLAR_GENERATOR_2, SlimefunItems.SOLAR_GENERATOR_3);
        Slimefun.registerResearch(new Research(186, "Upgraded Transmitters", 36, 15000, 0, 1), SlimefunItems.GPS_TRANSMITTER_2, SlimefunItems.GPS_TRANSMITTER_3);
        Slimefun.registerResearch(new Research(187, "Elevators", 28, 3500, 0, 1), SlimefunItems.ELEVATOR);
        Slimefun.registerResearch(new Research(188, "Full-Time Solar Power", 44, 15000, 0, 2), SlimefunItems.SOLAR_GENERATOR_4);
        Slimefun.registerResearch(new Research(189, "Top Tier Transmitter", 44, 20000, 0, 3), SlimefunItems.GPS_TRANSMITTER_4);
        Slimefun.registerResearch(new Research(190, "Energy Networks 101", 6, 2000, 1), SlimefunItems.ENERGY_REGULATOR);
        Slimefun.registerResearch(new Research(191, "Butcher Androids", 32, 12000, 2, 1), SlimefunItems.PROGRAMMABLE_ANDROID_BUTCHER);
        Slimefun.registerResearch(new Research(192, "Organic Food", 25, 6000, 2, 1), SlimefunItems.FOOD_FABRICATOR, SlimefunItems.ORGANIC_FOOD2, SlimefunItems.ORGANIC_FOOD3, SlimefunItems.ORGANIC_FOOD4, SlimefunItems.ORGANIC_FOOD5, SlimefunItems.ORGANIC_FOOD6, SlimefunItems.ORGANIC_FOOD7);
        Slimefun.registerResearch(new Research(193, "Automated Feeding", 25, 8000, 5, 1), SlimefunItems.AUTO_BREEDER);
        Slimefun.registerResearch(new Research(194, "Advanced Androids", 60, 20000, 3, 1), SlimefunItems.PROGRAMMABLE_ANDROID_2);
        Slimefun.registerResearch(new Research(195, "Advanced Androids - Butcher", 30, 15000, 5, 1), SlimefunItems.PROGRAMMABLE_ANDROID_2_BUTCHER);
        Slimefun.registerResearch(new Research(196, "Advanced Androids - Fisherman", 30, 15000, 5, 1), SlimefunItems.PROGRAMMABLE_ANDROID_2_FISHERMAN);
        Slimefun.registerResearch(new Research(197, "Animal Growth Manipulation", 32, 9000, 5, 1), SlimefunItems.ANIMAL_GROWTH_ACCELERATOR);
        Slimefun.registerResearch(new Research(198, "Exp Collector", 36, 6000, 3, 1), SlimefunItems.XP_COLLECTOR);
        Slimefun.registerResearch(new Research(199, "Organic Fertilizer", 36, 5000, 0, 1), SlimefunItems.FOOD_COMPOSTER, SlimefunItems.FERTILIZER2, SlimefunItems.FERTILIZER3, SlimefunItems.FERTILIZER4, SlimefunItems.FERTILIZER5, SlimefunItems.FERTILIZER6, SlimefunItems.FERTILIZER7, SlimefunItems.FERTILIZER8);
        Slimefun.registerResearch(new Research(200, "Crop Growth Acceleration", 40, 9000, 0, 1), SlimefunItems.CROP_GROWTH_ACCELERATOR);
        Slimefun.registerResearch(new Research(201, "Upgraded Crop Growth Accelerator", 44, 12000, 5, 1), SlimefunItems.CROP_GROWTH_ACCELERATOR_2);
        Slimefun.registerResearch(new Research(202, "Reactor Essentials", 36, 12000, 0, 1), SlimefunItems.REACTOR_COOLANT_CELL, SlimefunItems.NEPTUNIUM, SlimefunItems.PLUTONIUM);
        Slimefun.registerResearch(new Research(203, "Nuclear Power Plant", 48, 15000, 3, 1), SlimefunItems.NUCLEAR_REACTOR);
        Slimefun.registerResearch(new Research(204, "Mr Freeze", 20, 5000, 0, 1), SlimefunItems.FREEZER);
        Slimefun.registerResearch(new Research(205, "Cargo Basics", 30, 6000, 1), SlimefunItems.CARGO_MOTOR, SlimefunItems.CARGO_MANAGER, SlimefunItems.CARGO_NODE);
        Slimefun.registerResearch(new Research(206, "Cargo Setup", 30, 8000, 0, 1), SlimefunItems.CARGO_INPUT, SlimefunItems.CARGO_OUTPUT);
        Slimefun.registerResearch(new Research(207, "Electric Ingot Fabrication", 18, 6000, 3, 1), SlimefunItems.ELECTRIC_GOLD_PAN, SlimefunItems.ELECTRIC_DUST_WASHER, SlimefunItems.ELECTRIC_INGOT_FACTORY);
        Slimefun.registerResearch(new Research(208, "Faster Ingot Fabrication", 26, 8000, 3, 1), SlimefunItems.ELECTRIC_GOLD_PAN_2, SlimefunItems.ELECTRIC_DUST_WASHER_2, SlimefunItems.ELECTRIC_INGOT_FACTORY_2);
        Slimefun.registerResearch(new Research(209, "Super Fast Ingot Fabrication", 32, 12000, 5, 3), SlimefunItems.ELECTRIC_GOLD_PAN_3, SlimefunItems.ELECTRIC_DUST_WASHER_3, SlimefunItems.ELECTRIC_INGOT_FACTORY_3, SlimefunItems.ELECTRIC_ORE_GRINDER_2);
        Slimefun.registerResearch(new Research(210, "Automated Crafting", 20, 9000, 3, 1), SlimefunItems.AUTOMATED_CRAFTING_CHAMBER);
        Slimefun.registerResearch(new Research(211, "Upgraded Food Fabrication", 28, 6000, 3, 1), SlimefunItems.FOOD_FABRICATOR_2, SlimefunItems.FOOD_COMPOSTER_2);
        Slimefun.registerResearch(new Research(212, "Reactor Interaction", 18, 6500, 0, 1), SlimefunItems.REACTOR_ACCESS_PORT);
        Slimefun.registerResearch(new Research(213, "Fluid Pump", 28, 3500, 0, 1), SlimefunItems.FLUID_PUMP);
        Slimefun.registerResearch(new Research(214, "Upgraded Freezer", 29, 5000, 0, 1), SlimefunItems.FREEZER_2);
        Slimefun.registerResearch(new Research(215, "Never-Ending Circle", 30, 7500, 0, 1), SlimefunItems.BOOSTED_URANIUM);
        Slimefun.registerResearch(new Research(216, "Trash", 8, 1500, 1), SlimefunItems.TRASH_CAN);
        Slimefun.registerResearch(new Research(216, "Charging Bench", 8, 3500, 1), SlimefunItems.CHARGING_BENCH);
        Slimefun.registerResearch(new Research(217, "Advanced Output Node", 24, 5000, 0, 1), SlimefunItems.CARGO_OUTPUT_ADVANCED);
        Slimefun.registerResearch(new Research(218, "Carbon Press", 28, 6000, 0, 1), SlimefunItems.CARBON_PRESS);
        Slimefun.registerResearch(new Research(219, "Electric Smeltery", 28, 7500, 0, 1), SlimefunItems.ELECTRIC_SMELTERY);
        Slimefun.registerResearch(new Research(220, "Upgraded Electric Furnace", 20, 12000, 3, 1), SlimefunItems.ELECTRIC_FURNACE_2, SlimefunItems.ELECTRIC_FURNACE_3);
        Slimefun.registerResearch(new Research(221, "Upgraded Carbon Press", 26, 7500, 3, 1), SlimefunItems.CARBON_PRESS_2);
        Slimefun.registerResearch(new Research(222, "Empowered Androids", 60, 25000, 3, 1), SlimefunItems.PROGRAMMABLE_ANDROID_3);
        Slimefun.registerResearch(new Research(223, "Empowered Androids - Butcher", 30, 15000, 3, 1), SlimefunItems.PROGRAMMABLE_ANDROID_3_BUTCHER);
        Slimefun.registerResearch(new Research(224, "Empowered Androids - Fisherman", 30, 15000, 3, 1), SlimefunItems.PROGRAMMABLE_ANDROID_3_FISHERMAN);
        Slimefun.registerResearch(new Research(225, "Ultimate Carbon Press", 32, 12000, 0, 1), SlimefunItems.CARBON_PRESS_3);
        Slimefun.registerResearch(new Research(226, "Automated Wither Killer", 35, 25000, 3, 1), SlimefunItems.WITHER_ASSEMBLER);
        Slimefun.registerResearch(new Research(227, "Upgraded Heated Pressure Chamber", 20, 6000, 0, 1), SlimefunItems.HEATED_PRESSURE_CHAMBER_2);
        Slimefun.registerResearch(new Research(228, "Elytras", 20, 5000, 0, 1), SlimefunItems.ELYTRA_SCALE, SlimefunItems.ELYTRA);
        Slimefun.registerResearch(new Research(229, "Special Elytras", 30, 9000, 0, 1), SlimefunItems.INFUSED_ELYTRA, SlimefunItems.SOULBOUND_ELYTRA);
        Slimefun.registerResearch(new Research(230, "Electrified Crucible", 26, 7500, 0, 1), SlimefunItems.ELECTRIFIED_CRUCIBLE);
        Slimefun.registerResearch(new Research(231, "Hot Crucibles", 30, 10000, 3, 1), SlimefunItems.ELECTRIFIED_CRUCIBLE_2, SlimefunItems.ELECTRIFIED_CRUCIBLE_3);
        Slimefun.registerResearch(new Research(232, "Advanced Electric Smeltery", 28, 6500, 3, 1), SlimefunItems.ELECTRIC_SMELTERY_2);
        Slimefun.registerResearch(new Research(233, "Advanced Androids - Farmer", 30, 15000, 0, 1), SlimefunItems.PROGRAMMABLE_ANDROID_2_FARMER);
        Slimefun.registerResearch(new Research(234, "Lava Generator", 38, 12000, 0, 1), SlimefunItems.LAVA_GENERATOR);
        Slimefun.registerResearch(new Research(235, "Nether Ice Coolant", 45, 25000, 5, 1), SlimefunItems.NETHER_ICE, SlimefunItems.ENRICHED_NETHER_ICE, SlimefunItems.NETHER_ICE_COOLANT_CELL, SlimefunItems.NETHER_DRILL);
        Slimefun.registerResearch(new Research(236, "Nether Star Reactor", 60, 35000, 5, 1), SlimefunItems.NETHERSTAR_REACTOR);
    }
}
